// src/views/Blog.vue
<template>
    <section class="blogContainer">
        <h1 class="text-2xl font-bold">Blog</h1>
        <div>
            <template v-for="post in postsList" :key="post.id">
                <Post :src="post['cover_image']" :url="post.url" :tags="post['tag_list']">
                    <template #title>{{ post.title }}</template>
                    <template #desc>{{ post.description }}</template>
                </Post>
            </template>
        </div>
    </section>
</template>

<script setup>
import { onBeforeMount, ref } from 'vue';
import Post from '../components/Post.vue';

const postsList = ref([])

onBeforeMount(async () => {
    await fetch('https://dev.to/api/articles?username=webdavi').then(res => res.json()).then(res => {
        postsList.value = res
    })
})
</script>

<style scoped>
.blogContainer {
    @apply w-full h-max flex flex-col justify-center gap-12 items-center
}
.blogContainer > div{
    @apply w-full h-max flex flex-row flex-wrap justify-center gap-4
}
</style>

// src/sections/Blog/Blog.tsx
import { useEffect, useState } from "react";
import "./Blog.css";
export default function Welcome() {
    const [posts, setPosts] = useState([
        {
            id: 123,
            cover_image: "",
            title: "",
            description: "",
            tag_list: [],
            canonical_url: "",
        },
    ]);

    function getPostsData() {
        fetch("https://dev.to/api/articles?username=vuedavi")
            .then((res) => res.json())
            .then((data) => {
                setPosts(data);
            });
    }
    function redirectUser(url: string) {
        window.open(url, "_blank");
    }
    useEffect(() => {
        getPostsData();
    }, []);
    return (
        <section className="blogContainer">
            <h1>#Blog</h1>
            <div>
                {posts.map((post) => {
                    return (
                        <div key={post.id}>
                            <img src={post.cover_image} alt="post image" />
                            <div>
                                <h1>{post.title}</h1>
                                <p>{post.description}</p>
                                <div>
                                    {post.tag_list.map((tag) => {
                                        return <div>#{tag}</div>;
                                    })}
                                </div>
                                <button
                                    onClick={() =>
                                        redirectUser(post.canonical_url)
                                    }
                                >
                                    Saiba Mais
                                </button>
                            </div>
                        </div>
                    );
                })}
            </div>
        </section>
    );
}
